"""M6b shared-curvature null calibration validation (amendment2 Execution
step 2: "run the shared-curvature null first").

Reproducible evidence for the exhaustion-clause decision recorded in
`analysis/phase1_detectability.py` (`CONFIRMATORY_INFERENCE_RETIRED`): runs
BOTH amendment2 randomization methods -- the primary within-lifecycle
circular-shift reprojection (`_reprojected_rep`) and the pre-authorized
fallback stratified between-lifecycle sequence swap (`_stratified_swap_rep`)
-- against the MECHANISM-SPECIFIC shared-curvature null (no echo; common
sales/claims decay constant) for both components (lower, top) across the
three canonical seeds (4242, 77, 55), at the production pooling scale
(300 lifecycles) and production replicate count (1999).

A method/component is CALIBRATED on the shared-curvature null iff ZERO bins
are family-wise significant at alpha=0.05 for every seed. Any significant
bin on null data is a false positive.

Writes docs/reports/m6b_shared_curvature_null_validation.md and prints the
result matrix as JSON.

Usage:
    python scripts/m6b_null_validation.py [--reps 1999] [--n 300]
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import analysis.phase1_detectability as p1
from analysis.phase1_detectability import (
    PERMUTATION_ALPHA,
    _reprojected_rep,
    _stratified_swap_rep,
    build_lifecycles,
    fit_pooled_kernel,
)
from analysis.synthetic import simulate_panel_records

SEEDS = (4242, 77, 55)
METHODS = {
    "attempt1_circular_shift_reprojected": _reprojected_rep,
    "attempt2_stratified_swap": _stratified_swap_rep,
}
COMPONENTS = ("lower", "top")


def run_matrix(n_lifecycles: int, reps: int) -> dict:
    results: dict = {}
    original_rep_fn = p1._REP_FN
    try:
        for method_name, rep_fn in METHODS.items():
            p1._REP_FN = rep_fn
            for component in COMPONENTS:
                for seed in SEEDS:
                    t0 = time.time()
                    records = simulate_panel_records(
                        n_lifecycles=n_lifecycles,
                        lag_days=110.0,
                        inject_kernel=False,
                        seed=seed,
                        null_mode="shared_curvature",
                    )
                    kernel = fit_pooled_kernel(
                        build_lifecycles(records),
                        component=component,
                        exclude_noncash=False,
                        permutation_reps=reps,
                    )
                    sig = [
                        {"lag_bin": list(r.lag_bin), "rank_stat": r.rank_stat, "p_value": r.p_value}
                        for r in kernel
                        if r.significant()
                    ]
                    key = f"{method_name}/{component}/seed{seed}"
                    results[key] = {
                        "n_significant_bins": len(sig),
                        "significant_bins": sig,
                        "eligible_bins": sum(1 for r in kernel if r.p_value is not None),
                        "elapsed_s": round(time.time() - t0, 1),
                    }
                    print(json.dumps({key: results[key]}), flush=True)
    finally:
        p1._REP_FN = original_rep_fn
    return results


def write_report(results: dict, n_lifecycles: int, reps: int, path: Path) -> None:
    lines = [
        "# M6b shared-curvature null calibration validation",
        "",
        "Evidence of record for the exhaustion-clause decision in",
        "`analysis/phase1_detectability.py` (`CONFIRMATORY_INFERENCE_RETIRED`),",
        "per `docs/specs/m6b_panel_amendment2.md` Execution step 2. Generated by",
        f"`python scripts/m6b_null_validation.py --reps {reps} --n {n_lifecycles}`",
        "(deterministic; seeds 4242/77/55; shared-curvature null: common",
        "sales/claims exponential decay constant, independently timed claim",
        "bump, NO injected echo -- any family-wise-significant bin is a false",
        "positive).",
        "",
        "| method | component | seed | FW-significant bins (alpha=0.05) |",
        "|---|---|---|---|",
    ]
    verdicts: dict[str, bool] = {}
    for method_name in METHODS:
        for component in COMPONENTS:
            all_clear = True
            for seed in SEEDS:
                r = results[f"{method_name}/{component}/seed{seed}"]
                bins = (
                    ", ".join(
                        f"{b['lag_bin']} (p={b['p_value']:.4f})" for b in r["significant_bins"]
                    )
                    or "none"
                )
                lines.append(f"| {method_name} | {component} | {seed} | {bins} |")
                if r["n_significant_bins"] > 0:
                    all_clear = False
            verdicts[f"{method_name}/{component}"] = all_clear
    lines += ["", "## Calibration verdicts (zero false positives on every seed = CALIBRATED)", ""]
    for k, ok in verdicts.items():
        lines.append(f"- `{k}`: **{'CALIBRATED' if ok else 'FAILED'}**")
    lines += [
        "",
        "Per amendment2's exhaustion clause, confirmatory inference is",
        "authorized only for a method/component that is CALIBRATED above;",
        "\"if both calibrated randomization approaches fail, stop confirmatory",
        "inference and deliver a null-calibrated descriptive analysis without",
        "significant-bin claims.\"",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--reps", type=int, default=1999)
    ap.add_argument("--n", type=int, default=300)
    ap.add_argument(
        "--out", default="docs/reports/m6b_shared_curvature_null_validation.md"
    )
    args = ap.parse_args()
    results = run_matrix(args.n, args.reps)
    write_report(results, args.n, args.reps, Path(args.out))
    print(json.dumps({"alpha": PERMUTATION_ALPHA, "results": results}, indent=2))


if __name__ == "__main__":
    main()
